-- =============================================================
-- Technical + Building Specs seed — 9 categories
-- Generated: 2026-09-06T03:34:12.800Z
-- Run in phpMyAdmin > SQL tab against: abongsha_bongshai_app
-- =============================================================

-- Step 1: Remove ALL existing specs for these 9 categories
DELETE FROM `category_specs` WHERE `category_id` IN (37, 41, 44, 40, 39, 45, 46, 47, 51);

-- Step 2: Insert fresh Technical + Building specs
INSERT INTO `category_specs` (`category_id`, `spec_type`, `spec_key`, `spec_value`, `sort_order`, `created_at`, `updated_at`) VALUES
  (37, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (37, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (37, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (37, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (37, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (37, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (37, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (37, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength 12 MPa is used', 2, NOW(), NOW()),
  (37, 'building', 'OUTER WALL', '3 inch Reinforcement cement concrete panel/block is to be used', 3, NOW(), NOW()),
  (37, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (37, 'building', 'ROOF SLAB', 'Pre-cast 90mm reinforcement cement concrete panel is to be used.', 5, NOW(), NOW()),
  (37, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (37, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (37, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (37, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (37, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (37, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (37, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (37, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (41, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (41, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (41, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (41, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (41, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (41, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (41, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (41, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength 12 MPa is used', 2, NOW(), NOW()),
  (41, 'building', 'OUTER WALL', '3 inch Reinforcement cement concrete panel/block is to be used', 3, NOW(), NOW()),
  (41, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (41, 'building', 'ROOF SLAB', 'Pre-cast 90mm reinforcement cement concrete panel is to be used.', 5, NOW(), NOW()),
  (41, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (41, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (41, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (41, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (41, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (41, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (41, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (41, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (44, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (44, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (44, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (44, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (44, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (44, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (44, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (44, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength 12 MPa is used', 2, NOW(), NOW()),
  (44, 'building', 'OUTER WALL', '3 inch Reinforcement cement concrete panel/block is to be used', 3, NOW(), NOW()),
  (44, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (44, 'building', 'ROOF SLAB', 'Pre-cast 90mm reinforcement cement concrete panel is to be used.', 5, NOW(), NOW()),
  (44, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (44, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (44, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (44, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (44, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (44, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (44, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (44, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (40, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (40, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (40, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (40, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (40, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (40, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (40, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (40, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (40, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (40, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (40, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (40, 'building', 'MAIN DOOR', 'Chowkat Steel and palla steel is to be used', 6, NOW(), NOW()),
  (40, 'building', 'BEDROOM DOOR', 'Chowkat: Steel and Palla: steel is to be used', 7, NOW(), NOW()),
  (40, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (40, 'building', 'WINDOW', '3 x 4 ft size steel frame glass window to be used', 9, NOW(), NOW()),
  (40, 'building', 'FLOOR FINISHING', 'Net cement finishing on floor is used', 10, NOW(), NOW()),
  (40, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and cement plaster on wall to be used', 11, NOW(), NOW()),
  (40, 'building', 'BATHROOM FITTINGS', 'Standard uPVC fittings is to be used', 12, NOW(), NOW()),
  (40, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (39, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (39, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (39, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (39, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (39, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (39, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (39, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (39, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (39, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (39, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (39, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (39, 'building', 'MAIN DOOR', 'Chowkat Steel and palla steel is to be used', 6, NOW(), NOW()),
  (39, 'building', 'BEDROOM DOOR', 'Chowkat: Steel and Palla: steel is to be used', 7, NOW(), NOW()),
  (39, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (39, 'building', 'WINDOW', '3 x 4 ft size steel frame glass window to be used', 9, NOW(), NOW()),
  (39, 'building', 'FLOOR FINISHING', 'Net cement finishing on floor is used', 10, NOW(), NOW()),
  (39, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and cement plaster on wall to be used', 11, NOW(), NOW()),
  (39, 'building', 'BATHROOM FITTINGS', 'Standard uPVC fittings is to be used', 12, NOW(), NOW()),
  (39, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (45, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (45, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (45, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (45, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (45, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (45, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (45, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (45, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (45, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (45, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (45, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (45, 'building', 'MAIN DOOR', 'Chowkat Steel and palla steel is to be used', 6, NOW(), NOW()),
  (45, 'building', 'BEDROOM DOOR', 'Chowkat: Steel and Palla: steel is to be used', 7, NOW(), NOW()),
  (45, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (45, 'building', 'WINDOW', '3 x 4 ft size steel frame glass window to be used', 9, NOW(), NOW()),
  (45, 'building', 'FLOOR FINISHING', 'Net cement finishing on floor is used', 10, NOW(), NOW()),
  (45, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and cement plaster on wall to be used', 11, NOW(), NOW()),
  (45, 'building', 'BATHROOM FITTINGS', 'Standard uPVC fittings is to be used', 12, NOW(), NOW()),
  (45, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (46, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (46, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (46, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (46, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (46, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (46, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (46, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (46, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (46, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (46, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (46, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (46, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (46, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (46, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (46, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (46, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (46, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (46, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (46, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (47, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (47, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (47, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (47, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (47, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (47, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (47, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (47, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (47, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (47, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (47, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (47, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (47, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (47, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (47, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (47, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (47, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (47, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (47, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW()),
  (51, 'technical', 'CODES AND STANDARD', 'Comply with Bangladesh Nation Building Code (BNBC)', 1, NOW(), NOW()),
  (51, 'technical', 'EARTHQUAKE CONDITIONS', 'Earthquake resistant to magnitude 7.5', 2, NOW(), NOW()),
  (51, 'technical', 'WIND SPEED VALUE', 'Cyclone resistant 250 km/h (Must be fixed to the ground)', 3, NOW(), NOW()),
  (51, 'technical', 'CEMENT', 'Ordinary Portland Cement (OPC / CEM-I): Contains 95-100% clinker and 0-5% gypsum; graded by compressive strength (52.5 MPa). Brand SHAH CEMENT, AKIJ, CROWN, COSTAL PLAZ.', 4, NOW(), NOW()),
  (51, 'technical', 'MILD STEEL RODS', 'ASTM A36 grade Tensile Strength: 410 to 510 MPa. Brand BSRM/AKS/KSRM.', 5, NOW(), NOW()),
  (51, 'technical', 'STRUCTURAL STEEL', 'ASTM A36/SS400 grade Tensile Strength: 250 to 345 MPa.', 6, NOW(), NOW()),
  (51, 'building', 'FOOTING & SHORT COLUMN', 'Pre-cast footing is made of reinforced concrete; spreads the weight of a structure over a larger area on ground.', 1, NOW(), NOW()),
  (51, 'building', 'GROUND FLOOR', '3 inch pre-cast cement concrete block strength (1:3:6) is to be used', 2, NOW(), NOW()),
  (51, 'building', 'OUTER WALL', '3 inch concrete solid block is to be used', 3, NOW(), NOW()),
  (51, 'building', 'INNER WALL', '3 inch concrete solid block is to be used', 4, NOW(), NOW()),
  (51, 'building', 'ROOF CLADDING', 'High strength colour coated 0.4mm profile sheet to be used', 5, NOW(), NOW()),
  (51, 'building', 'MAIN DOOR', 'Chowkat Mehagoni wood and Mehagoni palla is to be used', 6, NOW(), NOW()),
  (51, 'building', 'BEDROOM DOOR', 'Chowkat: Mehagoni and Palla: ply wood flashdoor is to be used', 7, NOW(), NOW()),
  (51, 'building', 'SECURITY GRILL', '10mm square bar used', 8, NOW(), NOW()),
  (51, 'building', 'WINDOW', 'Standard size Thai Aluminum glass to be used', 9, NOW(), NOW()),
  (51, 'building', 'FLOOR TILES', '24 x 24 inch homogenous tiles on floor is used', 10, NOW(), NOW()),
  (51, 'building', 'BATHROOM TILES', '12 x 12 inch on floor and 12 x 10 inch on wall is used', 11, NOW(), NOW()),
  (51, 'building', 'BATHROOM FITTINGS', 'Standard metal fittings is to be used', 12, NOW(), NOW()),
  (51, 'building', 'ELECTRICAL WIRING', 'Standard wiring is to be used.', 13, NOW(), NOW());

-- Step 3: Verify row counts per category + spec_type
SELECT c.id, c.name, cs.spec_type, COUNT(*) AS row_count
FROM `categories` c
LEFT JOIN `category_specs` cs ON cs.category_id = c.id
WHERE c.id IN (37, 41, 44, 40, 39, 45, 46, 47, 51)
GROUP BY c.id, c.name, cs.spec_type
ORDER BY c.id, cs.spec_type;