const fs = require('fs');
const path = require('path');

const ALL_ROLES = ['superadmin', 'admin', 'editor', 'sales'];

const MODULE_DEFINITIONS = [
  { module: 'Executive Dashboard & Overview', path: '/admin', matchPath: '/admin', description: 'High-level KPI cards and stats' },
  { module: 'Customer Inquiries & CRM Leads', path: '/admin/leads*', matchPath: '/admin/leads', description: 'Quote requests, phone calls, contact submissions' },
  { module: 'Orders & Milestone Tracking', path: '/admin/orders*', matchPath: '/admin/orders', description: 'Client project orders, milestones, payments' },
  { module: 'Agent Directory & Approvals', path: '/admin/agents*', matchPath: '/admin/agents', description: 'Channel partners, applications, territory review' },
  { module: 'Agent Submitted Leads', path: '/admin/agent-leads*', matchPath: '/admin/agent-leads', description: 'Leads generated by field agents' },
  { module: 'Agent Invitation Campaigns', path: '/admin/agents/invite*', matchPath: '/admin/agents/invite', description: 'Excel/CSV bulk invitations, email templates' },
  { module: 'Product Catalog & Models', path: '/admin/products*', matchPath: '/admin/products', description: 'Steel building models, specs, pricing, gallery' },
  { module: 'Categories & Types', path: '/admin/categories*', matchPath: '/admin/categories', description: 'Simplex, Duplex, Triplex, Factory sheds' },
  { module: 'Completed & Ongoing Projects', path: '/admin/projects*', matchPath: '/admin/projects', description: 'Case studies, project portfolio, featured flags' },
  { module: 'Marketing Pages Content', path: '/admin/pages*', matchPath: '/admin/pages', description: 'Landing page copy, about, contact, calculator' },
  { module: 'Nationwide Service Areas', path: '/admin/service-areas*', matchPath: '/admin/service-areas', description: '64 Bangladesh districts, landing page generators' },
  { module: 'FAQs Management', path: '/admin/faqs*', matchPath: '/admin/faqs', description: 'Question/Answer knowledgebase' },
  { module: 'Team Members Directory', path: '/admin/team-members*', matchPath: '/admin/team-members', description: 'Company leadership and staff profiles' },
  { module: 'Testimonials & Reviews', path: '/admin/testimonials*', matchPath: '/admin/testimonials', description: 'Client quotes and feedback' },
  { module: 'Media Library', path: '/admin/media*', matchPath: '/admin/media', description: 'Asset uploads and image processor' },
  { module: 'Theme Studio Pro & Presets', path: '/admin/theme-editor*', matchPath: '/admin/theme-editor', description: 'Visual styling, presets, color palettes' },
  { module: 'SEO Automation & Audits', path: '/admin/seo*', matchPath: '/admin/seo', description: 'Technical audits, suggestions, batch generation' },
  { module: 'SEO Global API Settings', path: '/admin/seo/settings*', matchPath: '/admin/seo/settings', description: 'Groq/Cloud API keys, automated cron triggers' },
  { module: 'Admin Users & Accounts', path: '/admin/users*', matchPath: '/admin/users', description: 'Manage accounts, passwords, assign roles' },
  { module: 'Activity Audit Trail', path: '/admin/activity*', matchPath: '/admin/activity', description: 'System mutations and security logs' },
  { module: 'Role & Permission Audit', path: '/admin/roles', matchPath: '/admin/roles', description: 'Dynamic access control verification matrix' },
];

/**
 * Parses server/routes/admin.js source code to extract actual requireRole call arguments.
 * This guarantees the displayed RBAC matrix cannot drift from the true route gates.
 */
function getDynamicPermissionMatrix(adminRoutesFilePath) {
  const filePath = adminRoutesFilePath || path.join(__dirname, '../routes/admin.js');
  const source = fs.readFileSync(filePath, 'utf8');

  // 1. Extract CONTENT_SECTIONS array and its assigned requireRole(...)
  const contentSectionsMatch = source.match(/const\s+CONTENT_SECTIONS\s*=\s*\[([\s\S]*?)\];/);
  const contentRoleMatch = source.match(/CONTENT_SECTIONS\)\s*\{\s*router\.use\([^,]+,\s*requireRole\(([^)]+)\)\);/);

  const contentSections = new Set();
  let contentRoles = ['admin', 'superadmin', 'editor'];

  if (contentSectionsMatch) {
    const raw = contentSectionsMatch[1];
    const items = raw.match(/['"][^'"]+['"]/g) || [];
    for (const item of items) {
      contentSections.add(item.replace(/['"]/g, ''));
    }
  }

  if (contentRoleMatch) {
    const rawRoles = contentRoleMatch[1].match(/['"][^'"]+['"]/g) || [];
    contentRoles = rawRoles.map(r => r.replace(/['"]/g, ''));
  }

  // 2. Extract direct router.(get|post|use)(path, ...requireRole(...)...) gates
  const directGates = new Map();
  
  // Match each router.METHOD( ... ) call signature
  const methodRouteRegex = /router\.(get|post|put|delete|use)\s*\(\s*['"]([^'"]+)['"]\s*,([^;{]+)/g;
  let match;
  while ((match = methodRouteRegex.exec(source)) !== null) {
    const method = match[1];
    const routePath = match[2];
    const middlewareChain = match[3];
    const roleMatch = middlewareChain.match(/requireRole\s*\(([^)]+)\)/);
    if (roleMatch) {
      const rawRoles = roleMatch[1].match(/['"][^'"]+['"]/g) || [];
      const roles = rawRoles.map(r => r.replace(/['"]/g, ''));
      if (routePath && roles.length) {
        // GET routes define the main page view access for the module
        if (method === 'get' || !directGates.has(routePath)) {
          directGates.set(routePath, roles);
        }
      }
    }
  }

  // 3. Build dynamic matrix for all modules
  return MODULE_DEFINITIONS.map(def => {
    let resolvedRoles;

    if (directGates.has(def.matchPath)) {
      resolvedRoles = directGates.get(def.matchPath);
    } else if (contentSections.has(def.matchPath)) {
      resolvedRoles = contentRoles;
    } else {
      // Ungated route within /admin -> accessible to all logged-in roles
      resolvedRoles = ALL_ROLES;
    }

    // Sort roles in canonical order: superadmin, admin, editor, sales
    const sortedRoles = ALL_ROLES.filter(r => resolvedRoles.includes(r));

    return {
      module: def.module,
      path: def.path,
      roles: sortedRoles,
      description: def.description,
    };
  });
}

module.exports = {
  getDynamicPermissionMatrix,
  MODULE_DEFINITIONS,
  ALL_ROLES,
};
